@extends('layouts.site')

@section('content')
    <x-site.page-hero eyebrow="Engineering & Construction" heading="Engineering and construction shaped around clear project requirements." intro="Start with a project discussion so the Selotemna team can understand the site, scope and next step." :breadcrumbs="[['label' => 'Home', 'href' => route('home')], ['label' => 'Engineering & Construction']]" />

    <section class="section-space bg-white"><div class="site-container grid gap-12 lg:grid-cols-2 lg:gap-20"><x-site.section-heading eyebrow="Division introduction" heading="A practical route into a project conversation." intro="This division supports discussions around residential, commercial and real-estate development requirements. Detailed capability claims are published only when verified." /><div><h2 class="text-2xl font-semibold">General capability areas</h2><ul class="mt-6 grid gap-3 sm:grid-cols-2"><li class="feature-line">Residential projects</li><li class="feature-line">Commercial projects</li><li class="feature-line">Real-estate development requirements</li><li class="feature-line">Site and scope assessment</li><li class="feature-line">Construction enquiries</li><li class="feature-line">Project discussions</li></ul></div></div></section>

    <section class="section-space bg-ink-50"><div class="site-container"><x-site.section-heading eyebrow="Clients and requirements" heading="Begin with the proposed project." intro="Selotemna welcomes enquiries from individuals, families, businesses, property clients and development clients with a defined or emerging requirement." /><div class="mt-10 grid gap-6 md:grid-cols-3"><div class="plain-panel"><h3>1. Share the requirement</h3><p>Describe the project type, proposed location, current stage and broad scope.</p></div><div class="plain-panel"><h3>2. Discuss the site and scope</h3><p>The team reviews the information available and identifies what should be discussed next.</p></div><div class="plain-panel"><h3>3. Continue the enquiry</h3><p>Selotemna follows up through a configured contact channel to continue the project discussion.</p></div></div></div></section>

    <section class="section-space bg-white"><div class="site-container"><div class="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><x-site.section-heading eyebrow="Relevant projects" heading="Engineering and construction projects." intro="Project categories provide a consistent route to verified work when records are approved for publishing." /><a href="{{ route('projects.index') }}" class="text-link shrink-0">View All Projects</a></div><div class="mt-10"><x-site.project-tabs :groups="$projectGroups" id-prefix="engineering-projects" /></div></div></section>

    <x-site.conversion-cta heading="Discuss an engineering or construction requirement." intro="Contact Selotemna with the project type, proposed location, current stage and the scope information you already have." primary-label="Start a Project Enquiry" :primary-href="route('contact')" secondary-label="Explore Projects" :secondary-href="route('projects.index')" />
@endsection
